import { createContext,useCallback,useContext,useEffect,useMemo,useState } from 'react';import { api,getToken,setToken } from './api';import { connectSocket } from './socket';
const Context=createContext(null);export const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);const empty={tables:[],customers:[],products:[],orders:[],inventory:[],transactions:[],settings:{restaurant:'Orbe',city:'',serviceFee:10}};const lower=v=>String(v||'').toLowerCase();const sector={KITCHEN:'cozinha',BAR:'bar',GRILL:'churrasqueira',DESSERT:'sobremesa'};
function normalize({tables=[],orders=[],products=[],stock=[],customers=[],finance={}}){return{tables:tables.map(t=>({id:t.id,number:t.number,seats:t.seats,status:lower(t.status),note:t.note,customerId:t.tabs?.[0]?.customerId,openedAt:t.tabs?.[0]?.openedAt})),customers:customers.map(c=>({...c,visits:c.tabs?.length||0})),products:products.map(p=>({id:p.id,name:p.name,price:Number(p.price),category:p.category?.name||'',categoryId:p.categoryId,sector:sector[p.category?.sector]||'cozinha',available:p.available,image:p.imageUrl||'',description:p.description})),orders:orders.map(o=>({id:o.id,number:o.number,tableId:o.tab?.tableId,tabId:o.tabId,customerId:o.tab?.customerId,status:lower(o.status),createdAt:o.createdAt,startedAt:o.startedAt,items:o.items.map(i=>({productId:i.productId,qty:i.quantity,note:i.note||'',unitPrice:Number(i.unitPrice)}))})),inventory:stock.map(i=>({id:i.id,name:i.name,category:i.category,unit:i.unit,quantity:Number(i.quantity),min:Number(i.minimumStock)})),transactions:(finance.payments||[]).map(p=>({id:p.id,type:lower(p.type)==='withdrawal'?'withdrawal':lower(p.type)==='supply'?'supply':'sale',description:p.description||p.type,amount:(p.type==='WITHDRAWAL'?-1:1)*Number(p.amount),payment:lower(p.method),createdAt:p.createdAt})),settings:{restaurant:'Seu Restaurante',city:'',serviceFee:10},financeSession:finance.session};}
export function AppProvider({children}){const [data,setData]=useState(empty);const [user,setUser]=useState(null);const [ready,setReady]=useState(false);const [toast,setToast]=useState('');const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2600)};
 const refresh=useCallback(async()=>{if(!getToken())return;const [tables,orders,products,stock,customers,finance]=await Promise.all([api('/tables'),api('/orders'),api('/catalog/products'),api('/stock'),api('/customers'),api('/finance/summary')]);setData(normalize({tables,orders,products,stock,customers,finance}))},[]);
 useEffect(()=>{(async()=>{if(getToken())try{setUser(await api('/auth/me'));await refresh()}catch{setToken(null)}setReady(true)})()},[refresh]);useEffect(()=>user?connectSocket(()=>refresh()):undefined,[user,refresh]);
 async function login(email,password){const result=await api('/auth/login',{method:'POST',body:{email,password}});setToken(result.token);setUser(result.user);await refresh()}
 async function register(values){const result=await api('/auth/register',{method:'POST',body:values});setToken(result.token);setUser(result.user);await refresh()}
 function logout(){setToken(null);setUser(null);setData(empty)}
 async function mutate(collection,id,values){let path,body=values,method=id?'PUT':'POST';if(collection==='tables'){path=id?`/tables/${id}`:'/tables';body={...values,status:values.status?.toUpperCase()}}else if(collection==='inventory'){path=id?`/stock/${id}`:'/stock';body={...values,minimumStock:values.min}}else if(collection==='customers')path=id?`/customers/${id}`:'/customers';else if(collection==='products'){path=id?`/catalog/products/${id}`:'/catalog/products';body={...values,imageUrl:values.image,categoryId:values.categoryId||data.products[0]?.categoryId}}else if(collection==='transactions'){path='/finance/payments';body={type:values.type==='withdrawal'?'WITHDRAWAL':values.type==='supply'?'SUPPLY':'SALE',method:(values.payment||'cash').toUpperCase(),amount:Math.abs(values.amount),description:values.description};}else return;await api(path,{method,body});await refresh();notify('Registro salvo com sucesso.')}
 async function remove(collection,id){const base={tables:'/tables',inventory:'/stock',customers:'/customers',products:'/catalog/products'}[collection];if(!base)return;await api(`${base}/${id}`,{method:'DELETE'});await refresh();notify('Registro excluído.')}
 async function createOrder(values){const tab=await api(`/tables/${values.tableId}/open`,{method:'POST',body:{customerId:values.customerId||null}});const order=await api('/orders',{method:'POST',body:{tabId:tab.id,note:values.items[0]?.note,items:values.items.map(i=>({productId:i.productId,quantity:i.qty,note:i.note}))}});await refresh();notify('Pedido enviado para a cozinha.');return order}
 async function updateOrder(id,status){await api(`/orders/${id}/status`,{method:'PATCH',body:{status:status.toUpperCase()}});await refresh();notify('Status atualizado.')}
 async function moveStock(id,type,quantity,reason){await api(`/stock/${id}/movements`,{method:'POST',body:{type:type.toUpperCase(),quantity:Number(quantity),reason}});await refresh();notify('Movimentação registrada.')}
 async function openTable(id,customerId){const tab=await api(`/tables/${id}/open`,{method:'POST',body:{customerId:customerId||null}});await refresh();notify('Comanda aberta.');return tab}
 async function closeTable(id){const tab=await api(`/tables/${id}/close`,{method:'POST',body:{serviceFeePercent:data.settings.serviceFee}});await refresh();notify('Comanda fechada.');return tab}
 async function cashAction(action,body){const result=await api(`/finance/${action}`,{method:'POST',body});await refresh();notify('Caixa atualizado.');return result}
 const orderTotal=o=>(o?.items||[]).reduce((s,i)=>s+(i.unitPrice??data.products.find(p=>p.id===i.productId)?.price??0)*i.qty,0);const tableTotal=id=>data.orders.filter(o=>o.tableId===id&&o.status!=='cancelled').reduce((s,o)=>s+orderTotal(o),0);
 const value=useMemo(()=>({data,setData,user,ready,login,register,logout,refresh,reset:refresh,toast,notify,mutate,remove,createOrder,updateOrder,moveStock,openTable,closeTable,cashAction,orderTotal,tableTotal}),[data,user,ready,toast]);return <Context.Provider value={value}>{children}{toast&&<div className="toast">✓ {toast}</div>}</Context.Provider>}
export const useApp=()=>useContext(Context);
